### ISSUE TITLE
DeviceTensor.DimensionCount and INDArray.NDim should be renamed Rank

### ISSUE THREAD

**Issue by vermorel** [Lokad/Adrien#20]
The `DeviceTensor.DimensionCount` in `Adrien.Compiler.PlaidML` should be renamed `DeviceTensor.Rank` to be consistent with the rest of the solution. Idem, 

* `INDArray.NDim`
* `Shape.DimensionCount` 
* `Placeholder.DimensionCount`

**Comment by allisterb** [comment]
The types in the PlaidML namespace mirror the PlaidML C API functions so DimensionCount calls  [plaidml.__Internal.PlaidmlGetShapeDimensionCount](https://github.com/Lokad/Adrien/blob/29ec28f22d1228abfb8ff2ee8791e9a1b3341db1/src/spikes/2/Adrien.Compiler.PlaidML/Bindings.cs#L812). There is a Rank property on `DeviceTensor` however which is just an alias of DimensionCount, since `DeviceTensor` implements `IShape`.

**Comment by vermorel** [comment]
Closing spike 2 tickets.
